### ISSUE TITLE
Name passed via metadata to `TlsSecret` is ignored

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-plus#1664]
The following code:

```python
kplus.TlsSecret(self, 'MyTlsSecret',
  metadata=ApiObjectMetadata(name='override-secret-name'),
  tls_cert='cert',
  tls_key='key')

kplus.ConfigMap(self, 'MyConfigMap',
  metadata=ApiObjectMetadata(name='override-configmap-name'))
```

Produces this manifest:

```yaml
apiVersion: v1
kind: Secret
immutable: false
metadata:
  name: cdk8s-python-mytlssecret-c80b3170
stringData:
  tls.crt: cert
  tls.key: key
type: kubernetes.io/tls
---
apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  name: override-configmap-name
```

Notice how the name of the config map is `override-configmap-name` as given in the input, but the name of the secret is `cdk8s-python-mytlssecret-c80b3170` which is default auto-generated one, ignoring the one given in the input.
