### ISSUE TITLE
Chart.namespace shouldn't generate namespace field for cluster scope objects

### ISSUE THREAD

**Issue by shinebayar-g** [cdk8s-team/cdk8s-plus#4239]
### Description of the bug:

`Chart.namespace` shouldn't generate `.metadata.namespace` field for cluster level objects such as 
```yml
apiVersion: storage.k8s.io/v1
kind: StorageClass
```

### Reproduction Steps:

Given a chart

```ts
export class MyChart extends Chart {
    constructor(scope: App) {
        super(scope, 'my-chart', {
            namespace: 'something',
        });

        new KubeStorageClass(this, 'storage-class', {
            provisioner: 'kubernetes.io/gce-pd',
        });
    }
}
```

It generates

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  ...
  namespace: something
provisioner: kubernetes.io/gce-pd
```

while namespace is ignored by kubernetes, it would be nice if cdk8s didn't generate namespace. 

### Environment:

  - **Framework Version**: `"cdk8s": "^2.66.9"`, `"cdk8s-cli": "^2.133.0"`
  - **OS**:

### Other:

---

This is :bug: Bug Report
