### ISSUE TITLE
HttpIngressPath.pathType should not be optional

### ISSUE THREAD

**Issue by clauzf** [cdk8s-team/cdk8s-plus#63]
Under `./import/k8s.ts, `HttpIngressPath.pathType` is incorrectly set as optional. 

In the below generated yaml result, if pathType is missing, `kubectl apply` throws exception
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: ...
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
            path: /*
            pathType: Prefix <--- Must have
```

Exception
```
Error from server (Invalid): error when creating "XXXXX.yaml": Ingress.extensions "XXXXX-ingress-c8761513" is invalid: [spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified, spec.rules[0].http.paths[1].pathType: Required value: pathType must be specified]
```
