### ISSUE TITLE
Function to create Container Storage Interface (CSI) for Kubernetes

### ISSUE THREAD

**Issue by vumdao** [cdk8s-team/cdk8s-plus#767]
CDK8S+ should provide function to create Storage class, persitent volume and persistent volume claim which use `provisioner: efs.csi.aws.com` both dynamic and static PVC

Example:
```yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: af-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0f79ac6c652d70b55
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: af-efs-pg-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: af-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f79ac6c652d70b55::fsap-020740c5a04a6b113
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-airflow-postgresql
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: af-efs-sc
  volumeName: af-efs-pg-pv
  resources:
    requests:
      storage: 8Gi
```
