### ISSUE TITLE
Namespace not passed down in Subjects (Cluster Role Binding)

### ISSUE THREAD

**Issue by jaskerv** [cdk8s-team/cdk8s-plus#907]
The namespace associated with a service account is not exposed when added as a subject in a cluster role binding.

Code Outputs:
```
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: service-account-XXXX
```
Expected:
```
subjects:
  - kind: ServiceAccount
    name: service-account-XXXX
    namespace: namespace-XXXX
```
